meta_title: "Stiff Bicycles Factory | Le vélo de route sur-mesure"
meta_description: "Concevez le vélo route carbone de vos rêves. Assemblé en France et à prix d'usine."
meta_image: "home-stiff.png" # Une image dans votre dossier app/assets/images/
twitter_account: "@Stiffbicycles" # indispensable pour les Twitter Cards
