source 'https://rubygems.org'
ruby '2.3.1'

gem 'rails', '5.0.1'
gem 'rails-i18n'
gem 'devise-i18n'
gem 'puma'
gem 'pg'
gem 'figaro'
gem 'omniauth-facebook'
gem 'jbuilder', '~> 2.0'
gem 'devise'
gem 'redis'
gem 'stripe'
gem 'money-rails'
gem 'geocoder'
gem 'cloudinary', '1.1.0'
gem 'activeadmin', github: 'activeadmin/activeadmin'
gem 'inherited_resources', github: 'activeadmin/inherited_resources'
gem "pundit"

gem 'sass-rails'
gem 'jquery-rails'
gem 'uglifier'
gem 'bootstrap-sass'
gem 'font-awesome-sass'
gem 'simple_form'
gem 'autoprefixer-rails'
gem 'acts_as_votable', '~> 0.10.0'
gem 'perfect-scrollbar-rails'

gem "bootstrap-switch-rails"

group :development, :test do
  gem "letter_opener"
  gem 'binding_of_caller'
  gem 'better_errors'

  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'spring'
  gem 'listen', '~> 3.0.5'
  gem 'spring-watcher-listen', '~> 2.0.0'
end


